module.exports = [
  'signup',
  'login',
  'get-celestials',
  'get-my-celestials',
  'upgrade-facility',
  'start-research',
  'create-blueprint',
  'build-ships',
  'create-fleet',
  'land-fleet',
  'merge-fleets',
  'split-fleet',
  'generate-stars',
]